CREATE TABLE CITIES (
  CITY CHAR(20),
  STATE CHAR(20),
  PRIMARY KEY (CITY)
);

CREATE TABLE WAREHOUSES (
  WID INTEGER,
  WNAME CHAR(30),
  LOCATION CHAR(20),
  EXTRA JSON,
  PRIMARY KEY (WID),
  FOREIGN KEY (LOCATION)
    REFERENCES CITIES (CITY)
);

CREATE TABLE STORES (
  SID INTEGER,
  STORE_NAME CHAR(20),
  LOCATION_CITY CHAR(20),
  PRIMARY KEY (SID),
  FOREIGN KEY (LOCATION_CITY)
    REFERENCES WAREHOUSES (LOCATION)
);

CREATE TABLE CUSTOMER (
  CNO INTEGER,
  CNAME CHAR(50),
  ADDR VARCHAR(50),
  CU_CITY CHAR(20),
  PRIMARY KEY (CNO)
);

CREATE TABLE ORDERS (
  ONO INT,
  ODATE DATE,
  CNO INTEGER,
  PRIMARY KEY (ONO),
  FOREIGN KEY (CNO)
    REFERENCES CUSTOMER (CNO)
);

CREATE TABLE ITEMS (
  ITEMNO INTEGER,
  DESCRIPTION TEXT,
  WEIGHT DECIMAL(5,2),
  COST DECIMAL(5,2),
  PRIMARY KEY (ITEMNO)
);

CREATE TABLE ORDER_ITEMS (
  ONO INT,
  ITEMNO INT,
  ORDERED_QUANTITY INT,
  PRIMARY KEY (ONO, ITEMNO),
  FOREIGN KEY (ONO)
    REFERENCES ORDERS (ONO),
  FOREIGN KEY (ITEMNO)
    REFERENCES ITEMS (ITEMNO)
);

CREATE TABLE STORE_ITEMS (
  SID INT,
  ITEMNO INT,
  QUANTITY INT,
  PRIMARY KEY (SID, ITEMNO),
  FOREIGN KEY (SID)
    REFERENCES STORES (SID),
  FOREIGN KEY (ITEMNO)
    REFERENCES ITEMS (ITEMNO)
);
